### ISSUE TITLE
Persistent javax.net.ssl.SSLException - Connection reset thrown

### ISSUE THREAD

**Issue by sachafaust** [neo4j/neo4j-dotnet-driver#106]
I use LOAD CSV using SSL URI to reference the file hosted on Azure Storage. It works greath for tiny files but anything larger than ~500MB I regularely get the exception below. I implemented retry mechanism in vain. 

2016-08-26 07:17:21.424+0000 ERROR [o.n.b.v.r.i.ErrorReporter] Client triggered an unexpected error [UnknownError]: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset. See debug.log for more details, reference 13601142-61db-498b-a73d-75fd98e27672.
2016-08-26 07:17:21.424+0000 ERROR [o.n.b.v.r.i.ErrorReporter] Client triggered an unexpected error [UnknownError]: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset, reference 13601142-61db-498b-a73d-75fd98e27672. Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
    at sun.security.ssl.SSLSocketImpl.checkEOF(Unknown Source)
    at sun.security.ssl.AppInputStream.available(Unknown Source)
    at java.io.BufferedInputStream.available(Unknown Source)
    at sun.net.www.MeteredStream.available(Unknown Source)
    at sun.net.www.http.KeepAliveStream.close(Unknown Source)
    at java.io.FilterInputStream.close(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(Unknown Source)
    at java.io.PushbackInputStream.close(Unknown Source)
    at sun.nio.cs.StreamDecoder.implClose(Unknown Source)
    at sun.nio.cs.StreamDecoder.close(Unknown Source)
    at java.io.InputStreamReader.close(Unknown Source)
    at org.neo4j.csv.reader.Readables$3.close(Readables.java:134)
    at org.neo4j.csv.reader.ThreadAhead.close(ThreadAhead.java:66)
    at org.neo4j.csv.reader.BufferedCharSeeker.close(BufferedCharSeeker.java:302)
    at org.neo4j.cypher.internal.compiler.v3_0.spi.CSVResources$$anonfun$getCsvIterator$1.apply(CSVResources.scala:71)
    at org.neo4j.cypher.internal.compiler.v3_0.spi.CSVResources$$anonfun$getCsvIterator$1.apply(CSVResources.scala:70)
    at org.neo4j.cypher.internal.compiler.v3_0.TaskCloser$$anonfun$1.apply(TaskCloser.scala:43)
    at org.neo4j.cypher.internal.compiler.v3_0.TaskCloser$$anonfun$1.apply(TaskCloser.scala:41)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
    at scala.collection.immutable.List.flatMap(List.scala:344)
    at org.neo4j.cypher.internal.compiler.v3_0.TaskCloser.close(TaskCloser.scala:40)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:75)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.InterpretedExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:142)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.InterpretedExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:126)
    at org.neo4j.cypher.internal.compiler.v3_0.executionplan.InterpretedExecutionPlanBuilder$$anon$1.run(ExecutionPlanBuilder.scala:101)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor3_0.scala:224)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor3_0.scala:224)
    at org.neo4j.cypher.internal.compatibility.exceptionHandlerFor3_0$.runSafely(CompatibilityFor3_0.scala:139)
    at org.neo4j.cypher.internal.compatibility.CompatibilityFor3_0$ExecutionPlanWrapper.run(CompatibilityFor3_0.scala:223)
    at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:27)
    at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:111)
    at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:65)
    at org.neo4j.bolt.v1.runtime.internal.CypherStatementRunner.run(CypherStatementRunner.java:73)
    at org.neo4j.bolt.v1.runtime.internal.StandardStateMachineSPI.run(StandardStateMachineSPI.java:110)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine$State$2.runStatement(SessionStateMachine.java:122)
    at org.neo4j.bolt.v1.runtime.internal.SessionStateMachine.run(SessionStateMachine.java:653)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorkerFacade.lambda$run$3(SessionWorkerFacade.java:68)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.execute(SessionWorker.java:116)
    at org.neo4j.bolt.v1.runtime.internal.concurrent.SessionWorker.run(SessionWorker.java:77)
    at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
    at sun.security.ssl.Alerts.getSSLException(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
    at sun.security.ssl.AppInputStream.read(Unknown Source)
    at java.io.BufferedInputStream.read1(Unknown Source)
    at java.io.BufferedInputStream.read(Unknown Source)
    at sun.net.www.MeteredStream.read(Unknown Source)
    at java.io.FilterInputStream.read(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
    at java.io.FilterInputStream.read(Unknown Source)
    at java.io.PushbackInputStream.read(Unknown Source)
    at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at org.neo4j.csv.reader.SectionedCharBuffer.readFrom(SectionedCharBuffer.java:134)
    at org.neo4j.csv.reader.SectionedCharBuffer.readFrom(SectionedCharBuffer.java:123)
    at org.neo4j.csv.reader.Readables$3.read(Readables.java:126)
    at org.neo4j.csv.reader.ThreadAheadReadable.readAhead(ThreadAheadReadable.java:76)
    at org.neo4j.csv.reader.ThreadAhead.run(ThreadAhead.java:106)
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at sun.security.ssl.InputRecord.readFully(Unknown Source)
    at sun.security.ssl.InputRecord.read(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
    ... 17 more

**Comment by zhenlineo** [comment]
Sorry for not coming back to you earlier. 
May I ask what version of server and driver you are using?
I suppose error message is error logged in the server debug.log. Could you also give me the error message that you got on the client side?

**Comment by technige** [comment]
Closing due to staleness. Please re-open if more information is available.
