### ISSUE TITLE
"Win32Exception: The token supplied to the function is invalid" on default configuration

### ISSUE THREAD

**Issue by arturosevilla** [neo4j/neo4j-dotnet-driver#179]
I tried the following code:

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            // tried both 127.0.0.1 and localhost
            var rawDriver  = GraphDatabase.Driver("bolt://127.0.0.1:7687");
            using (var session = rawDriver.Session())
            {
                var result = session.Run("MATCH (n:Root) RETURN labels(n) AS labels");
                foreach (var row in result)
                {
                    Console.WriteLine(row["labels"].As<string[]>().FirstOrDefault());
                }
            }
     }
```

Over a Neo4j 3.2.0 Community Edition with default settings as follows:

```
#***************************************************************
# Server configuration
#***************************************************************

# This setting constrains all `LOAD CSV` import files to be under the `import` directory. Remove or uncomment it to
# allow files to be loaded from anywhere in filesystem; this introduces possible security problems. See the `LOAD CSV`
# section of the manual for details.
dbms.directories.import=import
dbms.allow_format_migration=true
# Require (or disable the requirement of) auth to access Neo4j
dbms.security.auth_enabled=false

#
# Bolt connector
#
dbms.connector.bolt.type=BOLT
dbms.connector.bolt.enabled=true
dbms.connector.bolt.tls_level=REQUIRED
# To have Bolt accept non-local connections, uncomment this line:
# dbms.connector.bolt.address=0.0.0.0:7687

#
# HTTP Connector
#
dbms.connector.http.type=HTTP
dbms.connector.http.enabled=true
#dbms.connector.http.encryption=NONE
# To have HTTP accept non-local connections, uncomment this line:
#dbms.connector.http.address=0.0.0.0:#{default.http.port}

#
# HTTPS Connector
#
# To enable HTTPS, uncomment these lines:
#dbms.connector.https.type=HTTP
#dbms.connector.https.enabled=true
#dbms.connector.https.encryption=TLS
#dbms.connector.https.address=localhost:#{default.https.port}

# Certificates directory
# dbms.directories.certificates=certificates

#*****************************************************************
# Administration client configuration
#*****************************************************************


# Comma separated list of JAX-RS packages containing JAX-RS resources, one
# package name for each mountpoint. The listed package names will be loaded
# under the mountpoints specified. Uncomment this line to mount the
# org.neo4j.examples.server.unmanaged.HelloWorldResource.java from
# neo4j-examples under /examples/unmanaged, resulting in a final URL of
# http://localhost:${default.http.port}/examples/unmanaged/helloworld/{nodeId}
#dbms.unmanaged_extension_classes=org.neo4j.examples.server.unmanaged=/examples/unmanaged

#*****************************************************************
# HTTP logging configuration
#*****************************************************************

# HTTP logging is disabled. HTTP logging can be enabled by setting this
# property to 'true'.
dbms.logs.http.enabled=false

# Logging policy file that governs how HTTP log output is presented and
# archived. Note: changing the rollover and retention policy is sensible, but
# changing the output format is less so, since it is configured to use the
# ubiquitous common log format
#org.neo4j.server.http.log.config=neo4j-http-logging.xml

# Enable this to be able to upgrade a store from an older version.
#dbms.allow_format_migration=true

# The amount of memory to use for mapping the store files, in bytes (or
# kilobytes with the 'k' suffix, megabytes with 'm' and gigabytes with 'g').
# If Neo4j is running on a dedicated server, then it is generally recommended
# to leave about 2-4 gigabytes for the operating system, give the JVM enough
# heap to hold all your transaction state and query context, and then leave the
# rest for the page cache.
# The default page cache memory assumes the machine is dedicated to running
# Neo4j, and is heuristically set to 50% of RAM minus the max Java heap size.
#dbms.memory.pagecache.size=10g

# Enable this to specify a parser other than the default one.
#cypher.default_language_version=2.0

# Keep logical logs, helps debugging but uses more disk space, enabled for
# legacy reasons To limit space needed to store historical logs use values such
# as: "7 days" or "100M size" instead of "true".
#dbms.tx_log.rotation.retention_policy=7 days

# Enable shell server so that remote clients can connect via Neo4j shell.
#dbms.shell.enabled=true
# The network interface IP the shell will listen on (use 0.0.0.0 for all interfaces).
#dbms.shell.host=127.0.0.1
# The port the shell will listen on, default is 1337.
#dbms.shell.port=1337
```

And my `packages.config` after `Install-Package Neo4j.Driver -Pre` is modified as follows (no other nuget package is installed):

```xml
<packages>
  <package id="Neo4j.Driver" version="1.3.0" targetFramework="net461" />
  <package id="System.Net.NameResolution" version="4.0.0" targetFramework="net461" />
  <package id="System.Net.Security" version="4.0.0" targetFramework="net461" />
  <package id="System.Net.Sockets" version="4.1.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.2.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.0.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.0.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.1.0" targetFramework="net461" />
</packages>
```

.NET target framework is 4.6.1.

And I get the following exception during `Session.Run()`:
```
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=Neo4j.Driver
  StackTrace:
   at Neo4j.Driver.Internal.Connector.PooledConnection.OnError(Exception error)
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.Init()
   at Neo4j.Driver.Internal.ConnectionPool.CreateNewPooledConnection()
   at Neo4j.Driver.Internal.ConnectionPool.<Acquire>b__21_0()
   at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func)
   at Neo4j.Driver.Internal.ConnectionPool.Acquire()
   at Neo4j.Driver.Internal.ConnectionPool.Acquire(AccessMode mode)
   at Neo4j.Driver.Internal.Session.<>c__DisplayClass14_0.<Run>b__0()
   at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func)
   at Neo4j.Driver.Internal.Session.Run(String statement, IDictionary`2 statementParameters)
   at TestNeoBolt.Program.Main(String[] args) in C:\Users\Administrator\Documents\Visual Studio 2017\Projects\TestNeoBolt\TestNeoBolt\Program.cs:line 19

Inner Exception 1:
SecurityException: Failed to establish encrypted connection with server bolt://127.0.0.1:7687/.

Inner Exception 2:
AuthenticationException: A call to SSPI failed, see inner exception.

Inner Exception 3:
Win32Exception: The token supplied to the function is invalid
```

With the following binding redirect:

```xml
      <dependentAssembly>
        <assemblyIdentity name="System.Security.Cryptography.X509Certificates" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" />
      </dependentAssembly>
```

It seems to be related to X509 handshake.

Is there a misconfiguration I'm missing or is it an issue within Neo4j or the driver?

**Comment by zhenlineo** [comment]
Hi,

Sorry for coming back late. I failed to reproduce your problem locally. Is the server using the neo4j self-generated certificate, or did you configured the server to use an existing certificate?

Zhen

**Comment by arturosevilla** [comment]
Out of the package with Neo4j Community

**Comment by zhenlineo** [comment]
Okay, thanks. I will look more into this. Meanwhile if you could try on other machine/os to help me check if it is more os related or it is a generally issue.

Regards,
Zhen

**Comment by ali-ince** [comment]
Hi,

We looked more into this issue and could not reproduce the problem mentioned. However, it seems that there may exist a local OS level issue about SSPI and TLS - which could be monitored via adding the following diagnostics configuration to the application configuration file (app.config or web.config) -
 please do not forget to update trace file location (c:\temp\network.log) to fit your environment.

```xml
<system.diagnostics>
    <sources>
      <source name="System.Net" tracemode="includehex" maxdatasize="1024">
        <listeners>
          <add name="System.Net"/>
        </listeners>
      </source>
      <source name="System.Net.Sockets">
        <listeners>
          <add name="System.Net"/>
        </listeners>
      </source>
    </sources>
    <switches>
      <add name="System.Net" value="Verbose"/>
      <add name="System.Net.Sockets" value="Verbose"/>
    </switches>
    <sharedListeners>
      <add name="System.Net"
        type="System.Diagnostics.TextWriterTraceListener"
        initializeData="c:\temp\network.log"
      />
    </sharedListeners>
    <trace autoflush="true"/>
  </system.diagnostics>
```

We will look at it in more depth after you are able to send us the trace file created. It will also be helpful for us if you could let us know your OS and Java version.

Regards,

Ali

**Comment by ali-ince** [comment]
Hi,

We have worked more on this upon another support issue about this same error where we have the exact configuration, we were able to reproduce it on our internal environment. The problem lies on the version of Windows being used and TLS 1.2's not being enabled. Neo4j server requires clients to support TLS 1.2 when encryption is used and the .NET Framework relies on OS-level security providers for protocol selection.

So, please verify that your windows version is listed as TLS 1.2 supported and enabled by default via [Support for SSL/TLS protocols on Windows](https://blogs.msdn.microsoft.com/kaushal/2011/10/02/support-for-ssltls-protocols-on-windows/). If it is not enabled, please perform the actions described at [How to enable TLS 1.2 on Windows Server 2008 R2](https://support.quovadisglobal.com/kb/a433/how-to-enable-tls-1_2-on-windows-server-2008-r2.aspx).

Regards,
Ali

**Comment by arturosevilla** [comment]
On some installations, even if you update Windows Server 2008 R2 and follow the TLS 1.2 activation instructions the same `Win32Exception` will be thrown. I have painfully detected that you need two KBs to be installed in those cases.

Make sure both KB3140245 and KB2888853 are installed, and also follow the TLS 1.2 activation within regedit.
