### ISSUE TITLE
`The Read method cannot be called when another read operation is pending.`

### ISSUE THREAD

**Issue by simendsjo** [neo4j/neo4j-dotnet-driver#329]
Sometimes we get the following in our test-suite when running lots of parallel
tests through Neo4jClient.

The tests seems to hang for a long time before the following exception is
thrown. I suspect a timeout on the socket as it takes a long time. Looks like
some sort of race-condition.

Not really sure how to best create a reproducible case... We basically do:

``` csharp
do {
  using (new TransactionScope(FollowAsync)) {
    var neo = new Graph();
    // Test case goes here
  }
  // Rollback called on dispose
} while (deadLockExceptionThrown) // if a deadlock was detected, run the entire test again
```

```
The Read method cannot be called when another read operation is pending.
```

```
   at Neo4j.Driver.Internal.Transaction.TransactionConnection.OnError(Exception error)
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.Sync()
   at Neo4j.Driver.Internal.Protocol.BoltProtocolV1.RollbackTransaction(IConnection connection)
   at Neo4j.Driver.Internal.Transaction.RollbackTx()
   at Neo4j.Driver.Internal.Transaction.Dispose(Boolean isDisposing)
   at Neo4j.Driver.Internal.StatementRunner.Dispose()
   at Neo4jClient.Transactions.BoltNeo4jTransaction.Dispose(Boolean isDisposing) in C:\Users\xsien\code\Neo4jClient\Neo4jClient.Full.Shared\Transactions\BoltNeo4jTransaction.cs:line 37
   at Neo4jClient.Transactions.BoltNeo4jTransaction.Dispose() in C:\Users\xsien\code\Neo4jClient\Neo4jClient.Full.Shared\Transactions\BoltNeo4jTransaction.cs:line 44
   at Neo4jClient.Transactions.BoltTransactionPromotableSinglePhasesNotification.Rollback(SinglePhaseEnlistment singlePhaseEnlistment) in C:\Users\xsien\code\Neo4jClient\Neo4jClient.Full.Shared\Transactions\Bolt\BoltTransactionPromotableSinglePhasesNotification.cs:line 89
   at System.Transactions.DurableEnlistmentAborting.EnterState(InternalEnlistment enlistment)
   at System.Transactions.TransactionStateAborted.EnterState(InternalTransaction tx)
   at System.Transactions.EnlistableStates.Timeout(InternalTransaction tx)
   at System.Transactions.Bucket.TimeoutTransactions()
   at System.Transactions.BucketSet.TimeoutTransactions()
   at System.Transactions.TransactionTable.ThreadTimer(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by simendsjo** [comment]
I get other similar errors too:

```
Exception: Neo4j.Driver.V1.ServiceUnavailableException: Connection with the server breaks due to IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.IO.IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.Net.Sockets.SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Neo4j.Driver.Internal.IO.ChunkReader.ReadNextMessages(Stream messageStream)
   at Neo4j.Driver.Internal.IO.MessageReader.Read(IMessageResponseHandler responseHandler)
   at Neo4j.Driver.Internal.Connector.SocketClient.ReceiveOne(IMessageResponseHandler responseHandler)
   at Neo4j.Driver.Internal.Connector.SocketConnection.ReceiveOne()
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.ReceiveOne()
   --- End of inner exception stack trace ---
   at Neo4jClient.BoltGraphClient.Neo4jClient.IRawGraphClient.ExecuteGetCypherResults[TResult](CypherQuery query) in C:\Users\xsien\code\Neo4jClient\Neo4jClient.Shared\BoltGraphClient.cs:line 564
   at Neo4jClient.Cypher.CypherFluentQuery`1.get_Results() in C:\Users\xsien\code\Neo4jClient\Neo4jClient.Shared\Cypher\CypherFluentQuery`TResult.cs:line 59
```

**Comment by ali-ince** [comment]
Hi @simendsjo,

`The Read method cannot be called when another read operation is pending.` message makes me think that the `Session` and/or `Transaction` object is being used concurrently by different threads - each trying to read some data from it. `Session` and `Transaction` objects are not thread-safe and thus should not be used concurrently.

`A blocking operation was interrupted by a call to WSACancelBlockingCall` seems also related as it points to a closed socket although another thread is still reading.

Both issues may be related with how Neo4j Driver is used in Neo4jClient project and as such I'm closing this issue since it would make more sense to open an issue at Neo4jClient rather than here.

Thanks.
