### ISSUE TITLE
System.ArgumentOutOfRangeException while creating session

### ISSUE THREAD

**Issue by Muzosh** [neo4j/neo4j-dotnet-driver#411]
I'm getting exception while trying to initialize simple synchronous session

**Neo4j Version:** 4.0.3 Community  
**Neo4j Mode**: Single instance  
**Driver version**: .NET driver 4.0.1
**Operating System:** Windows

### Steps to reproduce
1. Create .NET project, install Neo4j.Driver and Neo4j.Driver.Simple using nuget package manager
2. Copy code from screenshot
3. Run Neo4j server on localhost
3. Run project

screenshot:
![image](https://user-images.githubusercontent.com/30979983/79613786-81262d00-80ff-11ea-80db-dcc7a76b342f.png)

### Expected behavior
Session should be created.
### Actual behavior
Program falls on System.ArgumentOutOfRangeException.
Message: `Specified argument was out of the range of valid values.
Parameter name: Encountered  where IInternalDriver was expected`
stacktrace:
```
   at Neo4j.Driver.Internal.TypeExtensions.CastOrThrow[T](Object value)
   at Neo4j.Driver.DriverExtensions.Session(IDriver driver, Action`1 action)
   at test.Neo4jDriver.Run() in C:\Users\muzikant\source\repos\test\Program.cs:line 40
   at test.Program.Main(String[] args) in C:\Users\muzikant\source\repos\test\Program.cs:line 18
```
![image](https://user-images.githubusercontent.com/30979983/79613826-9b600b00-80ff-11ea-9b62-42b1c70542de.png)

**Comment by Muzosh** [comment]
Nevermind Im stupid, method Initialize has not been called, closing
