### ISSUE TITLE
Four integration tests are failing on 1.0

### ISSUE THREAD

**Issue by IngvarKofoed** [neo4j/neo4j-dotnet-driver#45]
Not sure why this is started. But if I clone a clean and fresh version of the driver, compile it from VS and run the unittests and integration tests. I have not changed anything on my system. Is using a VM only for Neo4j driver development and nothing else. So really not sure why thing has started to happen. Then 2 tests fails with the following:

```
Neo4j.Driver.IntegrationTests.ConnectionIT.ShouldEstablishConnectionWhenAuthEnabled [FAIL]
      System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Source\neo4j\temp\neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\bin\target\neo4j\neo4j-community-3.0.0-RC1\data\dbms\auth'.
      Stack Trace:
           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
           at System.IO.File.InternalDelete(String path, Boolean checkHost)
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\ConnectionIT.cs(108,0): at Neo4j.Driver.IntegrationTests.ConnectionIT.ShouldEstablishConnectionWhenAuthEnabled()

Neo4j.Driver.IntegrationTests.ConnectionIT.ShouldDoHandShake [FAIL]
      Neo4j.Driver.Exceptions.ClientException : Authentication token must contain: 'scheme : basic' (ID:3F430025A6B8848B03FBF94CBF4355A29D7EC42E0AC454665A746D84DBBBA868)
      Stack Trace:
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketConnection.cs(76,0): at Neo4j.Driver.Internal.Connector.SocketConnection.Sync()
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Session.cs(79,0): at Neo4j.Driver.Internal.Session.<>c__DisplayClass7_0.<Run>b__0()
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs(54,0): at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func)
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Session.cs(73,0): at Neo4j.Driver.Internal.Session.Run(String statement, IDictionary`2 statementParameters)
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\ConnectionIT.cs(57,0): at Neo4j.Driver.IntegrationTests.ConnectionIT.ShouldDoHandShake()

Neo4j.Driver.IntegrationTests.ConnectionIT.ShouldBeAbleToRunMultiStatementsInOneTransaction [FAIL]
      Neo4j.Driver.Exceptions.ClientException : Authentication token must contain: 'scheme : basic' (ID:3F430025A6B8848B03FBF94CBF4355A29D7EC42E0AC454665A746D84DBBBA868)
      Stack Trace:
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketConnection.cs(76,0): at Neo4j.Driver.Internal.Connector.SocketConnection.Sync()
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Transaction.cs(119,0): at Neo4j.Driver.Internal.Transaction.<>c__DisplayClass10_0.<Run>b__0()
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs(54,0): at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func)
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Transaction.cs(104,0): at Neo4j.Driver.Internal.Transaction.Run(String statement, IDictionary`2 parameters)
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\ConnectionIT.cs(136,0): at Neo4j.Driver.IntegrationTests.ConnectionIT.ShouldBeAbleToRunMultiStatementsInOneTransaction()

Neo4j.Driver.IntegrationTests.ConnectionIT.BuffersResultsOfOneQuerySoTheyCanBeReadAfterAnotherSubsequentQueryHasBeenParsed [FAIL]
      Neo4j.Driver.Exceptions.ClientException : Authentication token must contain: 'scheme : basic' (ID:3F430025A6B8848B03FBF94CBF4355A29D7EC42E0AC454665A746D84DBBBA868)
      Stack Trace:
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketConnection.cs(76,0): at Neo4j.Driver.Internal.Connector.SocketConnection.Sync()
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Session.cs(79,0): at Neo4j.Driver.Internal.Session.<>c__DisplayClass7_0.<Run>b__0()
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs(54,0): at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func)
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver\Internal\Session.cs(73,0): at Neo4j.Driver.Internal.Session.Run(String statement, IDictionary`2 statementParameters)
        neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\ConnectionIT.cs(155,0): at Neo4j.Driver.IntegrationTests.ConnectionIT.BuffersResultsOfOneQuerySoTheyCanBeReadAfterAnotherSubsequentQueryHasBeenParsed()
```

If I try to fix the first failing test (`System.IO.DirectoryNotFoundException`) by ckecking that the file exist before trying to delete it, then all but 1 test is working. Here is the exception:

```
Neo4j.Driver.IntegrationTests.ConnectionIT.ShouldEstablishConnectionWhenAuthEnabled [FAIL]
      FluentAssertions.Execution.AssertionFailedException : Expected string to start with
      "The credentials you provided were valid", but
      "The client is unauthorized due to authentication failure. (ID:4E78524151A93F700683E0A3681E0A623F19EF1A2DB2D9F8B9532BFF10BB4B50)" differs near "lie" (index 5).
```

I tried to reintroduce my WindowsProcessBasedNeo4jInstaller just to see if that would fix the issue. But it fails with the same test failings. 

WindowsProcessBasedNeo4jInstaller: https://github.com/IngvarKofoed/neo4j-dotnet-driver/blob/making-the-intergration-test-fixture-os-independed/Neo4j.Driver/Neo4j.Driver.IntegrationTests/Internals/WindowsProcessBasedNeo4jInstaller.cs

Help :)

**Comment by IngvarKofoed** [comment]
It seems that the commit https://github.com/neo4j/neo4j-dotnet-driver/commit/a6694dd7c0a919d4572b848d1c4209fde248a77b fixes all my issues :)

**Comment by IngvarKofoed** [comment]
I have apparently failed to notice that the integration tests uses a nightly build of the Neo4j server and this explains why it could stop work on my VM without any changes :)

**Comment by zhenlineo** [comment]
So glad you figured it out.
As you said, there are some changes in the server where they breaks the auth file location. But that is a bug and need to be fixed on server. The driver is affected but nothing should be fixed for the driver.

The reason we use snapshots/nightly build is because both the server and driver are still under construction. The link in driver's 1.0 branch will be changed once we got a stabilized server.

**Comment by zhenlineo** [comment]
My fix is a temp hack. please wait for this PR https://github.com/neo4j/neo4j/pull/6829 get merged.

**Comment by zhenlineo** [comment]
Close this issue thread as the PR  neo4j/neo4j#6829 get merged and the tests of this driver are back to green. Though we might re-encounter this problem again but then it would probably be another different error. So close this now and be free to re-open new ones when you have problem to run tests.
